### ISSUE TITLE
"gap" CSS property change

### ISSUE THREAD

**Issue by nameswastaken** [Freakybob-Team/freakybrowse#2]
This web browser relies on a Chromium 7X version afaik, but the gap CSS property for flex was added in Chromium 84.
![Image](https://github.com/user-attachments/assets/37c558ff-e98b-4319-8afe-554ee85ea8ae)

This may be the reason as to why the bottom menu options look odd, I _might_ plan to fix it if I get the time

**Comment by nameswastaken** [comment]
I should note im referencing the search.freakybob.site webpage

**Comment by 5quirre1** [comment]
PyQt6 fixed this

**Comment by nameswastaken** [comment]
aware

**Comment by nameswastaken** [comment]
k
